### ISSUE TITLE
newly assigned addresses cannot be used immediately

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/ip-range-localaddress-agent#1]
`net.connect()`ing with a newly created address as `localAddress` fails with an `EADDRNOTAVAIL` error:

```
ip-range-localaddress-agent:ip-pool adding address 10 <Buffer 2a 01 04 f8 0c 0c 6a 73 00 00 00 00 aa a6 00 06> 64 1652211641626 +1ms
  ip-range-localaddress-agent:ip-pool:tarn createSuccess 2a01:4f8:c0c:6a73::aaa6:0 +0ms
  ip-range-localaddress-agent:ip-pool:tarn acquireSuccess 2a01:4f8:c0c:6a73::aaa6:0 +0ms
  ip-range-localaddress-agent:connect {
  ip-range-localaddress-agent:connect   protocol: 'http:',
  ip-range-localaddress-agent:connect   hash: '',
  ip-range-localaddress-agent:connect   search: '',
  ip-range-localaddress-agent:connect   pathname: '/',
  ip-range-localaddress-agent:connect   href: 'http://localhost:37591/',
  ip-range-localaddress-agent:connect   port: 37591,
  ip-range-localaddress-agent:connect   host: 'localhost',
  ip-range-localaddress-agent:connect   secureEndpoint: false,
  ip-range-localaddress-agent:connect   localAddress: '2a01:4f8:c0c:6a73::aaa6:0',
  ip-range-localaddress-agent:connect   family: 0
  ip-range-localaddress-agent:connect } +0ms
Error: bind EADDRNOTAVAIL 2a01:4f8:c0c:6a73::aaa6:0
    at internalConnect (node:net:925:18)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:463:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1105:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:85:8) {
  errno: -99,
  code: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '2a01:4f8:c0c:6a73::aaa6:0'
}

Node.js v18.1.0
```

Curiously, `bind()`ing works after a delay, ~1-2s on my Linux 5.4 Hetzner VPS. 🤔

**Comment by derhuerst** [comment]
Running `ip monitor dev eth0` in parallel confirms that changes only go into effect after a ~1s:

```
2: eth0    inet6 2a01:4f8:c0c:6a73::aaa6:0/64 scope global tentative 
       valid_lft forever preferred_lft forever
# other logs…
# 1s pause
2: eth0    inet6 2a01:4f8:c0c:6a73::aaa6:0/64 scope global 
       valid_lft forever preferred_lft forever
local 2a01:4f8:c0c:6a73::aaa6:0 table local proto kernel metric 0 pref medium
```

**Comment by derhuerst** [comment]
@mildsunrise (Thanks for your efforts with `node_netlink`!) Do you know why this is the case? How would you debug this?

**Comment by mildsunrise** [comment]
Hi, I don't know much about the particular API you're accessing through netlink (rtnetlink) but I'd have expected that your request wouldn't be acknowledged until the IP has been installed. How much does the promise take to resolve?

Regardless, 1-2s to install an IP is a lot, I wonder what makes it take so much...

**Comment by derhuerst** [comment]
> […] I'd have expected that your request wouldn't be acknowledged until the IP has been installed. How much does the promise take to resolve?

It resolves almost immediately, and the IP address is assigned. But `bind()`ing to it still fails for another 1-2s.

I wonder if there is another "notification" coming in via (rt)netlink, signalling that the IP address is actually usable now; At least the additional lines logged by `ip monitor` (see above) seem to correlate with the ability to `bind()` to it.

I hacked together this script to observe this:

```js
import {networkInterfaces} from 'os'
import {connect} from 'net'

;(async () => {
	let _newAddr
	while (true) {
		const [newAddr] = networkInterfaces()
			// .eth0
			.enp0s8
			.filter(i => i.family === 6)
			.filter(i => i.address.includes('::aa'))
			.map(i => i.address)
			.sort()
			.slice(-1)
		if (newAddr !== _newAddr) {
			_newAddr = newAddr
			console.log(`${new Date().toISOString()} ${newAddr}`)

			let connecting = true
			console.time(newAddr)
			while (true) {
				const socket = connect({
					host: '::1',
					port: 8000,
					localAddress: newAddr,
				})
				await new Promise((resolve) => {
					socket.once('error', (err) => {
						console.error(err)
						resolve()
					})
					socket.once('connect', () => {
						connecting = false
						socket.destroy()
						resolve()
					})
				})

				if (!connecting) break
				await new Promise(r => setTimeout(r, 20))
			}
			console.timeEnd(newAddr)
		}

		await new Promise(r => setTimeout(r, 50))
	}
})()
.catch((err) => {
	console.error(err)
	process.exit(1)
})
```

**Comment by mildsunrise** [comment]
Interesting...

> I wonder if there is another "notification" coming in via (rt)netlink, signalling that the IP address is actually usable now; At least the additional lines logged by ip monitor (see above) seem to correlate with the ability to bind() to it.

Yes, there is. `ip monitor ...` listens for multicast notifications via rtnetlink, so the conclusion is that the kernel appears to reply with the acknowledgment immediately, but doesn't send the NEWADDR notification until the address is actually bindable.

You could replicate what `ip monitor ...` does by subscribing the socket to the appropriate [multicast group](https://netlink.alba.sh/docs/enums/rt_gen_structs.MulticastGroups.html), and waiting for the creation message to arrive. Example: https://github.com/mildsunrise/node_netlink/tree/ac57596525f#subscribing-to-multicast-groups-rtnetlink

**Comment by derhuerst** [comment]
> You could replicate what `ip monitor ...` does by subscribing the socket to the appropriate [multicast group](https://netlink.alba.sh/docs/enums/rt_gen_structs.MulticastGroups.html), and waiting for the creation message to arrive. Example: https://github.com/mildsunrise/node_netlink/tree/ac57596525f#subscribing-to-multicast-groups-rtnetlink

I tried that, but no messages came. 😞

```js
rtNetlinkSocket.socket.addMembership(rt.MulticastGroups.IPV4_IFADDR)
rtNetlinkSocket.socket.addMembership(rt.MulticastGroups.IPV6_IFADDR)
rtNetlinkSocket.on('message', message => {
	console.log('message', inspect(parse, {depth: 0}))
})
```

**Comment by mildsunrise** [comment]
quick inspection of iproute2 shows that it's actually subscribing to the NEXTHOP multicast group, not IP*_ADDR as it would be more intuitive

**Comment by derhuerst** [comment]
> quick inspection of iproute2 shows that it's actually subscribing to the NEXTHOP multicast group […]

no messages either :(

**Comment by mildsunrise** [comment]
hmm in that case I'm out of ideas... make sure you're using the latest version of node-netlink, since I fixed a related bug a while ago. the example I linked to has been tested, so if it doesn't work then maybe it's an IPv6 related quirk

**Comment by derhuerst** [comment]
Correction: It works with `rt.MulticastGroups.IPV6_IFADDR`!

I don't understand why it didn't work before, I don't remember doing things differently.
